# Generated by Django 5.1.1 on 2024-09-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=3000)),
                ('last_name', models.CharField(max_length=3000)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=3000)),
            ],
        ),
    ]
